# Generated by Django 4.2.28 on 2026-03-15 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='collaboration_description',
            field=models.TextField(blank=True, help_text='Describe what kind of RA collaboration you are looking for.'),
        ),
        migrations.AddField(
            model_name='research',
            name='open_for_collaboration',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='RAJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('ra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra_join_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra_join_requests', to='research.research')),
            ],
            options={
                'unique_together': {('research', 'ra')},
            },
        ),
    ]
