from django.db import models
from django.conf import settings
from apps.core.models import BaseModel


class Announcement(BaseModel):
    title = models.CharField(max_length=300)
    content = models.TextField()
    is_published = models.BooleanField(default=False, db_index=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="announcements"
    )
    published_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.title


class NewsPost(BaseModel):
    title = models.CharField(max_length=300)
    slug = models.SlugField(unique=True)
    body = models.TextField()
    cover_image = models.ImageField(upload_to="news/", null=True, blank=True)
    is_published = models.BooleanField(default=False, db_index=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="news_posts"
    )
    published_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-published_at"]

    def __str__(self):
        return self.title


class AuditLog(BaseModel):
    """Immutable record of every significant admin/platform action."""
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="audit_actions",
    )
    action = models.CharField(max_length=100, db_index=True)   # e.g. "user.approved"
    target_type = models.CharField(max_length=50, blank=True)  # e.g. "user", "research"
    target_id = models.UUIDField(null=True, blank=True)
    target_repr = models.CharField(max_length=300, blank=True) # human-readable description
    details = models.JSONField(default=dict, blank=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Audit Log"

    def __str__(self):
        return f"{self.actor} → {self.action} ({self.target_repr})"


class ReportExport(BaseModel):
    """Record of every CSV export generated by admins."""
    REPORT_TYPES = [
        ("members", "Members"),
        ("research", "Research"),
        ("events", "Events"),
        ("mentorship", "Mentorship"),
    ]

    report_type = models.CharField(max_length=50, choices=REPORT_TYPES)
    filters = models.JSONField(default=dict, blank=True)
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="report_exports",
    )
    row_count = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.report_type} export by {self.generated_by}"
