# Generated by Django 4.2.29 on 2026-03-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_add_conversations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conv_type',
            field=models.CharField(choices=[('user_admin', 'User ↔ Admin'), ('peer', 'Peer'), ('mentorship', 'Mentorship'), ('research_collab', 'Research Collaboration')], default='user_admin', max_length=20),
        ),
    ]
