import { useState } from 'react'
import { useQuery } from 'react-query'
import {
  Download, Loader2, Search, ChevronLeft, ChevronRight, ChevronDown,
} from 'lucide-react'
import { adminApi } from '@/api/admin'
import type { ReportType, ExportParams, AuditLogEntry } from '@/types/admin'
import { USER_ROLE_LABELS, USER_STATUS_LABELS } from '@/types/user'
import type { UserRole, UserStatus } from '@/types/user'
import { usePageTitle } from '@/hooks/usePageTitle'

// ── Report type config ────────────────────────────────────────────────────────

const REPORT_TYPES: Array<{ value: ReportType; label: string; description: string }> = [
  { value: 'members', label: 'Members', description: 'All registered users with role, status, and join date.' },
  { value: 'research', label: 'Research', description: 'All research submissions with category, status, and analytics.' },
  { value: 'events', label: 'Events', description: 'All events with type, registration counts, and dates.' },
  { value: 'mentorship', label: 'Mentorship', description: 'All mentorship requests with mentor, topic, and status.' },
]

const RESEARCH_STATUSES = ['draft', 'submitted', 'under_review', 'approved', 'rejected', 'published']
const RESEARCH_STATUS_LABELS: Record<string, string> = {
  draft: 'Draft', submitted: 'Submitted', under_review: 'Under Review',
  approved: 'Approved', rejected: 'Rejected', published: 'Published',
}

// ── Export history ────────────────────────────────────────────────────────────

function ExportHistory() {
  const { data, isLoading } = useQuery(
    'export-history',
    () => adminApi.listExportHistory().then((r) => r.data),
  )

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
      <div className="px-5 py-4 border-b border-gray-50">
        <h3 className="text-sm font-semibold text-gray-700">Export History</h3>
        <p className="text-xs text-gray-400 mt-0.5">Last 50 exports generated by admins.</p>
      </div>
      {isLoading ? (
        <div className="flex justify-center py-10"><Loader2 className="w-5 h-5 animate-spin text-gray-300" /></div>
      ) : !data?.length ? (
        <div className="py-10 text-center text-sm text-gray-400">No exports yet.</div>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-gray-50 border-b border-gray-100 text-xs text-gray-500 uppercase tracking-wide">
                <th className="text-left px-4 py-3 font-medium">Type</th>
                <th className="text-left px-4 py-3 font-medium">Rows</th>
                <th className="text-left px-4 py-3 font-medium">Filters</th>
                <th className="text-left px-4 py-3 font-medium">Generated By</th>
                <th className="text-left px-4 py-3 font-medium">Date</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {data.map((exp) => (
                <tr key={exp.id} className="hover:bg-gray-50/50">
                  <td className="px-4 py-3">
                    <span className="inline-flex items-center gap-1 rounded-full bg-teal-50 px-2.5 py-0.5 text-xs font-medium text-[#0D9488] capitalize">
                      {exp.report_type}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-gray-700 font-medium">{exp.row_count}</td>
                  <td className="px-4 py-3 text-xs text-gray-400 max-w-xs">
                    {Object.entries(exp.filters)
                      .filter(([, v]) => v)
                      .map(([k, v]) => `${k}: ${v}`)
                      .join(', ') || '—'}
                  </td>
                  <td className="px-4 py-3 text-xs text-gray-600">{exp.generated_by_name ?? '—'}</td>
                  <td className="px-4 py-3 text-xs text-gray-400">
                    {new Date(exp.created_at).toLocaleDateString()} {new Date(exp.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}

// ── Audit Log ─────────────────────────────────────────────────────────────────

const ACTION_LABEL_MAP: Record<string, string> = {
  'user.approved': 'User Approved',
  'user.rejected': 'User Rejected',
  'user.suspended': 'User Suspended',
  'user.role_changed': 'Role Changed',
  'research.published': 'Research Published',
  'research.approved': 'Research Approved',
  'research.rejected': 'Research Rejected',
  'announcement.created': 'Announcement Created',
  'announcement.updated': 'Announcement Updated',
  'announcement.deleted': 'Announcement Deleted',
  'news.created': 'News Created',
  'news.updated': 'News Updated',
  'news.deleted': 'News Deleted',
  'report.exported': 'Report Exported',
  'contact.resolved': 'Contact Resolved',
  'mentorship.matched': 'Mentorship Matched',
}

function AuditLogTable() {
  const [search, setSearch] = useState('')
  const [actionFilter, setActionFilter] = useState('')
  const [page, setPage] = useState(1)

  const { data, isLoading, isFetching } = useQuery(
    ['audit-log', search, actionFilter, page],
    () =>
      adminApi
        .listAuditLog({ search: search || undefined, action: actionFilter || undefined, page })
        .then((r) => r.data),
    { keepPreviousData: true },
  )

  const totalPages = Math.ceil((data?.count ?? 0) / 20)

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
      <div className="px-5 py-4 border-b border-gray-50">
        <h3 className="text-sm font-semibold text-gray-700">Audit Log</h3>
        <p className="text-xs text-gray-400 mt-0.5">Full trail of admin and platform actions.</p>
      </div>

      {/* Filters */}
      <div className="px-4 py-3 border-b border-gray-50 flex flex-wrap gap-3 items-center">
        <div className="relative flex-1 min-w-48">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <input
            value={search}
            onChange={(e) => { setSearch(e.target.value); setPage(1) }}
            placeholder="Search by actor or target…"
            className="w-full rounded-xl border border-gray-200 bg-white pl-9 pr-4 py-2.5 text-sm text-gray-900 placeholder:text-gray-400 transition-all duration-150 focus:outline-none focus:ring-2 focus:ring-[#0D9488]/40 focus:border-[#0D9488] hover:border-gray-300"
          />
        </div>
        <div className="relative">
          <select
            value={actionFilter}
            onChange={(e) => { setActionFilter(e.target.value); setPage(1) }}
            className="w-full rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm text-gray-900 placeholder:text-gray-400 transition-all duration-150 focus:outline-none focus:ring-2 focus:ring-[#0D9488]/40 focus:border-[#0D9488] hover:border-gray-300 appearance-none pr-10 cursor-pointer"
          >
            <option value="">All actions</option>
            {Object.entries(ACTION_LABEL_MAP).map(([v, l]) => (
              <option key={v} value={v}>{l}</option>
            ))}
          </select>
          <ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
        </div>
        {isFetching && <Loader2 className="w-4 h-4 animate-spin text-gray-400" />}
      </div>

      {isLoading ? (
        <div className="flex justify-center py-10"><Loader2 className="w-5 h-5 animate-spin text-gray-300" /></div>
      ) : !data?.results.length ? (
        <div className="py-10 text-center text-sm text-gray-400">No audit log entries found.</div>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-gray-50 border-b border-gray-100 text-xs text-gray-500 uppercase tracking-wide">
                <th className="text-left px-4 py-3 font-medium">Action</th>
                <th className="text-left px-4 py-3 font-medium">Target</th>
                <th className="text-left px-4 py-3 font-medium">Actor</th>
                <th className="text-left px-4 py-3 font-medium">Timestamp</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {data.results.map((entry: AuditLogEntry) => (
                <tr key={entry.id} className="hover:bg-gray-50/50">
                  <td className="px-4 py-3">
                    <span className="text-xs font-medium text-gray-700">
                      {ACTION_LABEL_MAP[entry.action] ?? entry.action}
                    </span>
                    {entry.target_type && (
                      <span className="ml-1.5 text-xs text-gray-400 capitalize">({entry.target_type})</span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-xs text-gray-500 max-w-xs truncate">
                    {entry.target_repr || '—'}
                  </td>
                  <td className="px-4 py-3">
                    <div className="text-xs text-gray-700">{entry.actor_name ?? 'System'}</div>
                    {entry.actor_email && (
                      <div className="text-xs text-gray-400">{entry.actor_email}</div>
                    )}
                  </td>
                  <td className="px-4 py-3 text-xs text-gray-400 whitespace-nowrap">
                    {new Date(entry.created_at).toLocaleDateString()}{' '}
                    {new Date(entry.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {data && data.count > 20 && (
        <div className="flex items-center justify-between px-4 py-3 border-t border-gray-100 text-sm text-gray-500">
          <span>Page {page} of {totalPages} · {data.count} total</span>
          <div className="flex gap-1">
            <button onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page === 1}
              className="rounded-lg p-1.5 hover:bg-gray-100 disabled:opacity-40">
              <ChevronLeft className="w-4 h-4" />
            </button>
            <button onClick={() => setPage((p) => Math.min(totalPages, p + 1))} disabled={page === totalPages}
              className="rounded-lg p-1.5 hover:bg-gray-100 disabled:opacity-40">
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

// ── Main Reports Page ─────────────────────────────────────────────────────────

export default function Reports() {
  usePageTitle('Reports')
  const [tab, setTab] = useState<'export' | 'history' | 'audit'>('export')

  // Export form state
  const [reportType, setReportType] = useState<ReportType>('members')
  const [dateFrom, setDateFrom] = useState('')
  const [dateTo, setDateTo] = useState('')
  const [roleFilter, setRoleFilter] = useState('')
  const [statusFilter, setStatusFilter] = useState('')
  const [exporting, setExporting] = useState(false)
  const [exportError, setExportError] = useState('')

  const selectedReport = REPORT_TYPES.find((r) => r.value === reportType)!

  const handleExport = async () => {
    setExporting(true)
    setExportError('')
    try {
      const params: ExportParams = {
        type: reportType,
        date_from: dateFrom || undefined,
        date_to: dateTo || undefined,
        role: roleFilter || undefined,
        status: statusFilter || undefined,
      }
      const response = await adminApi.exportReport(params)
      // Trigger browser download
      const blob = new Blob([response.data as BlobPart], { type: 'text/csv' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${reportType}_report_${new Date().toISOString().slice(0, 10)}.csv`
      a.click()
      URL.revokeObjectURL(url)
    } catch {
      setExportError('Export failed. Please try again.')
    } finally {
      setExporting(false)
    }
  }

  return (
    <div className="max-w-6xl mx-auto px-4 py-8 space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-xl font-bold text-gray-900">Reports & Exports</h1>
        <p className="text-sm text-gray-500 mt-0.5">Generate CSV reports and view the platform audit trail.</p>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 bg-gray-100 rounded-xl p-1 w-fit">
        {([
          { value: 'export', label: 'Export Reports' },
          { value: 'history', label: 'Export History' },
          { value: 'audit', label: 'Audit Log' },
        ] as const).map((t) => (
          <button
            key={t.value}
            onClick={() => setTab(t.value)}
            className={`rounded-lg px-4 py-1.5 text-sm font-medium transition-colors ${
              tab === t.value ? 'bg-white shadow-sm text-[#093344]' : 'text-gray-500 hover:text-gray-700'
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* ── Export tab ── */}
      {tab === 'export' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
          {/* Report type selector */}
          <div className="space-y-2">
            <h3 className="text-sm font-medium text-gray-700">Report Type</h3>
            {REPORT_TYPES.map((rt) => (
              <button
                key={rt.value}
                onClick={() => { setReportType(rt.value); setRoleFilter(''); setStatusFilter('') }}
                className={`w-full text-left rounded-xl border p-3 transition-colors ${
                  reportType === rt.value
                    ? 'border-[#0D9488] bg-teal-50'
                    : 'border-gray-100 bg-white hover:bg-gray-50'
                }`}
              >
                <p className="text-sm font-medium text-gray-900">{rt.label}</p>
                <p className="text-xs text-gray-400 mt-0.5">{rt.description}</p>
              </button>
            ))}
          </div>

          {/* Filters + download */}
          <div className="lg:col-span-2 bg-white rounded-2xl border border-gray-100 shadow-sm p-6 space-y-5">
            <div>
              <h3 className="text-sm font-semibold text-gray-700 mb-1">
                {selectedReport.label} Report
              </h3>
              <p className="text-xs text-gray-400">{selectedReport.description}</p>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5">Date From</label>
                <input
                  type="date"
                  value={dateFrom}
                  onChange={(e) => setDateFrom(e.target.value)}
                  className="w-full rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm text-gray-900 placeholder:text-gray-400 transition-all duration-150 focus:outline-none focus:ring-2 focus:ring-[#0D9488]/40 focus:border-[#0D9488] hover:border-gray-300"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5">Date To</label>
                <input
                  type="date"
                  value={dateTo}
                  onChange={(e) => setDateTo(e.target.value)}
                  className="w-full rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm text-gray-900 placeholder:text-gray-400 transition-all duration-150 focus:outline-none focus:ring-2 focus:ring-[#0D9488]/40 focus:border-[#0D9488] hover:border-gray-300"
                />
              </div>
            </div>

            {/* Role filter (members only) */}
            {reportType === 'members' && (
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">Filter by Role</label>
                  <div className="relative">
                    <select
                      value={roleFilter}
                      onChange={(e) => setRoleFilter(e.target.value)}
                      className="w-full rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm text-gray-900 placeholder:text-gray-400 transition-all duration-150 focus:outline-none focus:ring-2 focus:ring-[#0D9488]/40 focus:border-[#0D9488] hover:border-gray-300 appearance-none pr-10 cursor-pointer"
                    >
                      <option value="">All roles</option>
                      {(Object.keys(USER_ROLE_LABELS) as UserRole[]).map((r) => (
                        <option key={r} value={r}>{USER_ROLE_LABELS[r]}</option>
                      ))}
                    </select>
                    <ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">Filter by Status</label>
                  <div className="relative">
                    <select
                      value={statusFilter}
                      onChange={(e) => setStatusFilter(e.target.value)}
                      className="w-full rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm text-gray-900 placeholder:text-gray-400 transition-all duration-150 focus:outline-none focus:ring-2 focus:ring-[#0D9488]/40 focus:border-[#0D9488] hover:border-gray-300 appearance-none pr-10 cursor-pointer"
                    >
                      <option value="">All statuses</option>
                      {(Object.keys(USER_STATUS_LABELS) as UserStatus[]).map((s) => (
                        <option key={s} value={s}>{USER_STATUS_LABELS[s]}</option>
                      ))}
                    </select>
                    <ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                  </div>
                </div>
              </div>
            )}

            {/* Research status filter */}
            {reportType === 'research' && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5">Filter by Status</label>
                <div className="relative">
                  <select
                    value={statusFilter}
                    onChange={(e) => setStatusFilter(e.target.value)}
                    className="w-full rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm text-gray-900 placeholder:text-gray-400 transition-all duration-150 focus:outline-none focus:ring-2 focus:ring-[#0D9488]/40 focus:border-[#0D9488] hover:border-gray-300 appearance-none pr-10 cursor-pointer"
                  >
                    <option value="">All statuses</option>
                    {RESEARCH_STATUSES.map((s) => (
                      <option key={s} value={s}>{RESEARCH_STATUS_LABELS[s]}</option>
                    ))}
                  </select>
                  <ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                </div>
              </div>
            )}

            {/* Applied filters summary */}
            <div className="rounded-xl bg-gray-50 px-4 py-3 text-xs text-gray-500 space-y-1">
              <p className="font-medium text-gray-600">Export will include:</p>
              <p>• Report type: <span className="font-medium text-gray-700">{selectedReport.label}</span></p>
              {dateFrom && <p>• From: <span className="font-medium text-gray-700">{dateFrom}</span></p>}
              {dateTo && <p>• To: <span className="font-medium text-gray-700">{dateTo}</span></p>}
              {roleFilter && <p>• Role: <span className="font-medium text-gray-700">{USER_ROLE_LABELS[roleFilter as UserRole]}</span></p>}
              {statusFilter && <p>• Status: <span className="font-medium text-gray-700">{statusFilter}</span></p>}
              {!dateFrom && !dateTo && !roleFilter && !statusFilter && (
                <p>• All records (no filters applied)</p>
              )}
            </div>

            {exportError && (
              <p className="text-xs text-red-600">{exportError}</p>
            )}

            <button
              onClick={handleExport}
              disabled={exporting}
              className="inline-flex items-center gap-2 rounded-xl bg-[#093344] hover:bg-[#0D9488] px-6 py-2.5 text-sm font-semibold text-white shadow-sm transition-all duration-200 disabled:opacity-50"
            >
              {exporting
                ? <Loader2 className="w-4 h-4 animate-spin" />
                : <Download className="w-4 h-4" />
              }
              {exporting ? 'Generating…' : 'Download CSV'}
            </button>
          </div>
        </div>
      )}

      {/* ── History tab ── */}
      {tab === 'history' && <ExportHistory />}

      {/* ── Audit log tab ── */}
      {tab === 'audit' && <AuditLogTable />}
    </div>
  )
}
