# Generated by Django 4.2.29 on 2026-03-15 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorship', '0002_update_mentorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorfeedback',
            name='feedback_text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ResearchCollabRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_requests_as_requester', to=settings.AUTH_USER_MODEL)),
                ('research_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_requests_as_ra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchCollaboration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration', to='mentorship.researchcollabrequest')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_as_requester', to=settings.AUTH_USER_MODEL)),
                ('research_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_as_ra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
